# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

# namespace to deploy all Resources to
namespace: open-cluster-management

# list of Resource Config to be Applied
resources:
  - example-multicloudhub-cr.yaml